services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - spamassassin

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  spamassassin:
    build:
      context: ./spamassassin
    container_name: spamassassin
    ports:
      - "783:783"
    restart: unless-stopped
